default_platform(:android)

platform :android do
  desc 'Build AAB and upload to Google Play Store'
  lane :deploy do |options|
    track = options[:track] || 'internal'

    sh("scripts/gplay_build.sh", "flutter build appbundle --release --flavor gplay --dart-define=SUBSCRIPTIONS_ENABLED=true")

    supply(
      track: track,
      aab: 'build/app/outputs/bundle/gplayRelease/app-gplay-release.aab',
      metadata_path: 'fastlane/metadata/android',
    )
  end
end
